[platformio]
default_envs = esp32

[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino

build_flags =
    -D GG_DEBUG=0                   ; Enable debug logging in the library (set to 0 to disable)

;upload_port = COM5                 ; Uncomment and set the correct port if auto-detection fails    
upload_protocol = esptool
;monitor_port = COM5                ; Uncomment and set the correct port if auto-detection fails
monitor_speed = 115200

;this option is strongly recommended for this example 
monitor_filters = esp32_exception_decoder           ; Set for ANSI color support in serial monitor

